from pathlib import Path
import json
import joblib
import pandas as pd


# ============================================================
# FLOODWATCH CURRENT / LATEST AVAILABLE FORECAST
# ============================================================

ML_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = ML_DIR / "data"

FORECAST_DIR = DATA_DIR / "forecast"
MODEL_DIR = DATA_DIR / "models"

DATASET = FORECAST_DIR / "forecast_dataset.csv"
METADATA = MODEL_DIR / "flood_forecast_metadata.json"

OUTPUT = FORECAST_DIR / "latest_forecast.json"


# ============================================================
# CONFIGURATION
# ============================================================

# Current model is trained on the Naraj/Cuttack study region.
TARGET_LAT = 20.50
TARGET_LON = 85.95

MODEL_NAME = "Naraj/Cuttack, Odisha"

# Risk thresholds
HIGH_THRESHOLD = 0.75
MODERATE_THRESHOLD = 0.50


# ============================================================
# RISK CLASSIFICATION
# ============================================================

def classify_risk(probability):

    probability = float(probability)

    if probability >= HIGH_THRESHOLD:
        return "HIGH"

    if probability >= MODERATE_THRESHOLD:
        return "MODERATE"

    return "LOW"


# ============================================================
# RISK DESCRIPTION
# ============================================================

def risk_description(risk):

    descriptions = {
        "LOW": (
            "Low predicted flood risk during this forecast horizon."
        ),
        "MODERATE": (
            "Moderate predicted flood risk. "
            "Monitor rainfall and water-level trends."
        ),
        "HIGH": (
            "High predicted flood risk. "
            "Close monitoring of local hydrological conditions is recommended."
        )
    }

    return descriptions.get(
        risk,
        "Flood-risk prediction generated by the AI model."
    )


# ============================================================
# LOAD MODEL FEATURES
# ============================================================

def load_metadata():

    if not METADATA.exists():
        raise FileNotFoundError(
            f"Forecast metadata not found:\n{METADATA}"
        )

    metadata = json.loads(
        METADATA.read_text(
            encoding="utf-8"
        )
    )

    features = metadata.get(
        "features",
        []
    )

    horizons = metadata.get(
        "forecast_horizons_hours",
        metadata.get(
            "horizons_hours",
            [6, 12, 24]
        )
    )

    if not features:
        raise RuntimeError(
            "No model features found in metadata."
        )

    return metadata, features, horizons


# ============================================================
# LOAD DATASET
# ============================================================

def load_dataset():

    if not DATASET.exists():
        raise FileNotFoundError(
            f"Forecast dataset not found:\n{DATASET}"
        )

    print("\nLoading forecast dataset...")

    df = pd.read_csv(
        DATASET,
        parse_dates=["timestamp"]
    )

    if df.empty:
        raise RuntimeError(
            "Forecast dataset is empty."
        )

    df = (
        df.sort_values("timestamp")
        .reset_index(drop=True)
    )

    print(
        f"Rows: {len(df):,}"
    )

    print(
        "Latest timestamp:",
        df["timestamp"].max()
    )

    return df


# ============================================================
# BUILD CURRENT FEATURE VECTOR
# ============================================================

def build_feature_vector(df, features):

    missing_features = [
        feature
        for feature in features
        if feature not in df.columns
    ]

    if missing_features:

        raise RuntimeError(
            "The following model features are missing:\n"
            + "\n".join(missing_features)
        )

    # --------------------------------------------------------
    # IMPORTANT:
    #
    # Use ONLY the latest row.
    #
    # Every feature in this row was constructed using
    # observations available at or before this timestamp.
    # --------------------------------------------------------

    row = df.iloc[-1]

    timestamp = row["timestamp"]

    x = pd.DataFrame(
        [[
            pd.to_numeric(
                row[feature],
                errors="coerce"
            )
            for feature in features
        ]],
        columns=features
    )

    nan_count = int(
        x.isna().sum().sum()
    )

    print(
        "\nFeature count:",
        len(features)
    )

    print(
        "NaN features:",
        nan_count
    )

    if nan_count > 0:

        missing = [
            feature
            for feature in features
            if pd.isna(
                pd.to_numeric(
                    row[feature],
                    errors="coerce"
                )
            )
        ]

        print("\nMissing/invalid features:")

        for feature in missing:
            print(
                " ",
                feature
            )

        raise RuntimeError(
            "Current feature vector contains NaN values."
        )

    return x, timestamp


# ============================================================
# PREDICT ONE HORIZON
# ============================================================

def predict_horizon(
    horizon,
    x
):

    model_path = (
        MODEL_DIR
        / f"flood_forecast_{horizon}h.pkl"
    )

    imputer_path = (
        MODEL_DIR
        / f"flood_forecast_{horizon}h_imputer.pkl"
    )

    if not model_path.exists():

        raise FileNotFoundError(
            f"Model not found:\n{model_path}"
        )

    if not imputer_path.exists():

        raise FileNotFoundError(
            f"Imputer not found:\n{imputer_path}"
        )

    model = joblib.load(
        model_path
    )

    imputer = joblib.load(
        imputer_path
    )

    x_imputed = imputer.transform(
        x
    )

    probability = float(
        model.predict_proba(
            x_imputed
        )[0, 1]
    )

    # Protect against floating-point values
    # slightly outside [0,1].
    probability = max(
        0.0,
        min(
            1.0,
            probability
        )
    )

    risk = classify_risk(
        probability
    )

    return {
        "horizon_hours": int(horizon),

        "flood_probability": round(
            probability,
            6
        ),

        "flood_probability_percent": round(
            probability * 100,
            2
        ),

        "risk": risk,

        "description": risk_description(
            risk
        ),

        "status": "predicted"
    }


# ============================================================
# MAIN
# ============================================================

def main():

    print("=" * 80)
    print("FLOODWATCH CURRENT FLOOD FORECAST")
    print("=" * 80)

    # --------------------------------------------------------
    # Load metadata
    # --------------------------------------------------------

    metadata, features, horizons = (
        load_metadata()
    )

    # --------------------------------------------------------
    # Load dataset
    # --------------------------------------------------------

    df = load_dataset()

    # --------------------------------------------------------
    # Build current feature vector
    # --------------------------------------------------------

    x, timestamp = build_feature_vector(
        df,
        features
    )

    # --------------------------------------------------------
    # Location
    # --------------------------------------------------------

    print("\nForecast study location:")
    print(
        f"{MODEL_NAME} "
        f"({TARGET_LAT}, {TARGET_LON})"
    )

    print("\nObservation time:")
    print(timestamp)

    # --------------------------------------------------------
    # Result object
    # --------------------------------------------------------

    result = {

        "status": "success",

        "mode": "latest_available_historical",

        "model": {
            "name": "FloodWatch Future Flood Forecast",
            "algorithm": "Random Forest",
            "study_region": MODEL_NAME,
            "feature_count": len(features)
        },

        "location": {
            "latitude": TARGET_LAT,
            "longitude": TARGET_LON,
            "region": MODEL_NAME
        },

        "observation_time": str(
            timestamp
        ),

        "forecast": {},

        "data_source": {
            "rainfall": "CWC historical dataset",
            "water_level": "CWC historical dataset"
        },

        "forecast_horizons_hours": [
            int(h)
            for h in horizons
        ],

        "warning": (
            "This is an AI/ML flood-risk forecast "
            "generated from the latest available "
            "CWC observation in the local historical "
            "dataset. It is not a live government "
            "flood warning."
        ),

        "model_scope": (
            "The temporal forecasting model was "
            "trained using the Naraj/Cuttack study "
            "region in Odisha. It should not be "
            "interpreted as a fully India-wide "
            "calibrated forecasting model."
        )
    }

    # --------------------------------------------------------
    # Predict 6h / 12h / 24h
    # --------------------------------------------------------

    for horizon in horizons:

        print(
            "\n" + "-" * 80
        )

        print(
            f"Predicting next {horizon} hours..."
        )

        prediction = predict_horizon(
            horizon,
            x
        )

        probability = (
            prediction[
                "flood_probability"
            ]
        )

        risk = prediction[
            "risk"
        ]

        print(
            f"Probability: {probability:.6f}"
        )

        print(
            f"Probability (%): "
            f"{prediction['flood_probability_percent']:.2f}%"
        )

        print(
            f"Risk: {risk}"
        )

        result["forecast"][
            f"{horizon}h"
        ] = prediction

    # --------------------------------------------------------
    # Overall risk
    # --------------------------------------------------------

    probabilities = [
        result["forecast"][
            f"{h}h"
        ]["flood_probability"]
        for h in horizons
    ]

    maximum_probability = max(
        probabilities
    )

    overall_risk = classify_risk(
        maximum_probability
    )

    result["overall_risk"] = {

        "risk": overall_risk,

        "maximum_probability": round(
            maximum_probability,
            6
        ),

        "maximum_probability_percent": round(
            maximum_probability * 100,
            2
        ),

        "description": risk_description(
            overall_risk
        )
    }

    # --------------------------------------------------------
    # Save JSON
    # --------------------------------------------------------

    OUTPUT.write_text(
        json.dumps(
            result,
            indent=2
        ),
        encoding="utf-8"
    )

    # --------------------------------------------------------
    # Print result
    # --------------------------------------------------------

    print(
        "\n" + "=" * 80
    )

    print(
        "FORECAST RESULT"
    )

    print(
        "=" * 80
    )

    print(
        json.dumps(
            result,
            indent=2
        )
    )

    print(
        "\n" + "=" * 80
    )

    print(
        "Forecast saved:"
    )

    print(
        OUTPUT
    )

    print(
        "=" * 80
    )


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()